### ISSUE TITLE
Documentation is severely lacking

### ISSUE THREAD

**Issue by vityok** [tpapp/lla#17]
Hi Tamas,

thanks for your great work. However, documentation for LLA is severely lacking as you can see [here](https://www.reddit.com/r/lisp/comments/3eejtp/matrices_and_friends/cti2bx9?context=3).

Could you please provide a simple how-to for starters that would walk through a simple application doing basic linear algebra tasks (like multiplying vectors and matrices, etc.)?

Thanks!
Victor

**Comment by tpapp** [comment]
I am not planning to work on LLA in the medium run, so your best chance is looking at the tests.
